### ISSUE TITLE
Error uploading article page image

### ISSUE THREAD

**Issue by barisakpunar** [KalikoCMS/DemoSite.Mvc#1]
Server Error in '/' Application.

Property TopImage not found!

Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: System.Exception: Property TopImage not found!

Source Error: 

An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.

Stack Trace: 

[Exception: Property TopImage not found!]
   KalikoCMS.Core.Collections.PropertyCollection.set_Item(String propertyName, PropertyData value) +198
   KalikoCMS.Core.EditablePage.SetProperty(String propertyName, PropertyData value) +83
   KalikoCMS.Admin.Content.EditPage.SavePropertiesForPage(EditablePage editablePage) +1393
   KalikoCMS.Admin.Content.EditPage.SaveDataForNewPage() +205
   KalikoCMS.Admin.Content.EditPage.SaveData() +194
   KalikoCMS.Admin.Content.EditPage.PublishButtonEventHandler(Object sender, EventArgs e) +104
   System.Web.UI.WebControls.LinkButton.RaisePostBackEvent(String eventArgument) +153
   System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint) +3804

Version Information: Microsoft .NET Framework Version:4.0.30319; ASP.NET Version:4.0.30319.34249

**Comment by fschultz** [comment]
I'm very sorry I haven't answered this before now. There seems to been something wrong with the issue notification setup :(

Just wanted to check if this worked out or if there's anything I can help with?

**Comment by barisakpunar** [comment]
Thank you. I have solved this problem by changing the property name different. The uppercase "I" in the property name was making problem. As I remember when system was converting it to lowercase letters property names was not matching. If you need I can try to reproduce error.

**Comment by fschultz** [comment]
If you have the time that would be much appreciated, thanks!

**Comment by barisakpunar** [comment]
The problem is as  follows.

In PropertyCollection class when it is matching the property items method uses propertyName.ToLowerInvariant() to match.
    
    internal PropertyItem GetItem(string propertyName) {          
            return Properties.Find(p => p.PropertyName == propertyName.ToLowerInvariant());
        }

But normally properties are filled  in PropertyData class with using ToLower()

    select new PropertyItem {
                            PagePropertyId = m.PagePropertyId,
                            PropertyName = p.Name.ToLower(),
                            PropertyData = CreatePropertyData(p.PropertyTypeId, m.PageData),
                            PropertyId = p.PropertyId,
                            PropertyTypeId = p.PropertyTypeId
                        };

In the TopImage property 
İn my computer ToLowerInvariant() returns "topimage" 
But ToLower() returns "topımage" with no dot over 'i

So they dont match with ant throws an error " Additional information: Property TopImage not found!"

**Comment by fschultz** [comment]
Thank you very much for getting my attention to this problem and the descriptive bug report!

I will go through the complete project to ensure that the invariant version of the function is used so that strings are converted in a culture independent manner also in other parts of the system.

**Comment by fschultz** [comment]
Version 1.1.1 just released should fix this issue.

**Comment by Matthew-Bonner** [comment]
Please close, this is no longer an issue and it was fixed in January last year.
