### ISSUE TITLE
when deployed this site on virtual directory, many errors

### ISSUE THREAD

**Issue by dusdong** [KalikoCMS/DemoSite.Mvc#6]
when deployed this site on virtual directory, many errors:
1, links. example: /search.
2. css: example: DemoSite.css
3. admin
...

**Comment by fschultz** [comment]
Thanks for the feedback! Fixed the search link by using site settings instead of hard code it and the CSS reference to include root. Code updated.

Content links (such as the link to admin in the feature properties) needs to be changed manually if using a virtual directory.

**Comment by dusdong** [comment]
Thank you, the 1-2 problem solved, but the question of 3 have manye problem:
1、Use http://localhost/DemoSite.Mvc/Login.aspx login, the page auto skip to http://localhost/Admin/Content/ is error.
2、Visit http://localhost/DemoSite.Mvc/Admin/Content/ , all js and css is error.

**Comment by dusdong** [comment]
I test the search result page, return page link is error. 
Is still is: http://localhost/news/2015/updated-to-kaliko-cms-1-1-0/

**Comment by fschultz** [comment]
Forgot to mention that you also need to update the **adminPath** attribute of the **siteSettings** element in web.config to reflect the path including the virtual path (**adminPath="/DemoSite.Mvc/Admin/"**). See http://kaliko.com/cms/get-started/installation/ for more information about the web.config.

You also need to reindex all pages in the search engine. This is done by going to the search section within the admin and click on the reindex-button.

Hope that solves the remaining issues.

**Comment by dusdong** [comment]
Great! This issue is solved! Thank you!
